# Generated by Django 2.2.6 on 2019-10-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='style',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='info_text',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='motion_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='theme_add',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='theme_top',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
