# Generated by Django 2.2.6 on 2019-11-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_meta_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('int', models.IntegerField(null=True)),
                ('str', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='motion',
            name='theme_add',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='theme_top',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
