# Generated by Django 2.2.6 on 2019-11-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191102_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='info',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='str',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
