# Generated by Django 2.2.6 on 2019-11-06 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_motion_copy_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='copy_num',
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 40, 35, 221029))),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Motion')),
            ],
        ),
    ]
