# Generated by Django 2.2.6 on 2019-11-06 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191106_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='motion',
        ),
        migrations.AddField(
            model_name='copy',
            name='motion_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='copy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 45, 4, 372291)),
        ),
    ]
