# Generated by Django 2.2.6 on 2019-11-09 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191106_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='copy_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='copy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 20, 58, 26, 227249)),
        ),
    ]
