# Generated by Django 2.2.6 on 2019-11-25 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191109_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='deprecated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 23, 42, 26, 874115)),
        ),
        migrations.AlterField(
            model_name='round',
            name='is_preliminary',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
