# Generated by Django 3.0.2 on 2020-02-15 14:48

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200215_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='easy_gov',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='motion',
            name='easy_opp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='motion',
            name='fair',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='motion',
            name='fairness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motion',
            name='leaning_gov',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AddField(
            model_name='motion',
            name='leaning_opp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='copy',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 23, 48, 56, 685764)),
        ),
    ]
